#headless service

apiVersion: v1
kind: Service
metadata:
  name: mysql-headless
  labels:
    app: mysql 
    tier: db  
    project: expense
spec:
  ports:
  - protocol: TCP 
    port: 3306
    targetPort: 3306   
  clusterIP: None
  selector:
    app: mysql 
    tier: db 
    project: expense

--- 

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql  # has to match .spec.template.metadata.labels
      tier: db 
      project: expense
  serviceName: "mysql-headless"
  replicas: 1 # by default is 1
  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        app: mysql # has to match .spec.selector.matchLabels
        tier: db 
        project: expense
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mysql
        image: santhoshdatti/mysql:1.0.0 
        volumeMounts:
        - name: mysql
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: mysql
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "ebs-sc"
      resources:
        requests:
          storage: 1Gi